### ISSUE TITLE
Unable to track time on circuit 

### ISSUE THREAD

**Issue by bitamar** [Gizra/productivity#229]
I'm getting this:
![screen shot 2016-02-15 at 9 18 23 am](https://cloud.githubusercontent.com/assets/2283680/13042024/2ce048d4-d3c5-11e5-9cc5-e51fd1e9c5e9.png)

That's the request causing the error:
```
Request URL:http://live-productivity.pantheon.io/api/tracking
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:104.239.201.60:80
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Authorization, access-token, Content-Type
Access-Control-Allow-Origin:*
Age:0
Cache-Control:no-cache, must-revalidate, post-check=0, pre-check=0
Connection:keep-alive
Content-Length:183
Content-Type:application/problem+json; charset=utf-8
Date:Mon, 15 Feb 2016 07:19:22 GMT
Expires:Sun, 19 Nov 1978 05:00:00 GMT
Server:nginx
Vary:Accept
Via:1.1 varnish-v4
X-Api-Version:v1.0
X-Content-Type-Options:nosniff
X-Pantheon-Styx-Hostname:styxacf2847e
X-Styx-Build-Date:Tue Sep  8 20:14:49 UTC 2015
X-Styx-Build-Num:975
X-Styx-Build-Sha:75058451cd2e622496298f556cda4ba5248e3ab6
X-Styx-Req-Id:styx-24007fa7301cfd83d7935b75073667b1
X-Styx-Version:StyxGo
X-Varnish:599515413
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,he;q=0.6,de;q=0.4
access-token: -- removed --
Connection:keep-alive
Content-Length:469
Content-Type:text/plain;charset=UTF-8
DNT:1
Host:live-productivity.pantheon.io
Origin:http://productivity.gizra.com
Referer:http://productivity.gizra.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Request Payload
view source
{period: "hour", type: "regular", length: 3.5,…}
day: "14"
employee: "itamar"
issues: [{issue: 13401, label: "#1444: Script for deploying migration data", type: "dev", time: 1},…]
length: 3.5
month: 2
period: "hour"
projectID: "27"
type: "regular"
year: 2016
Name
tracking
tracking
2 requests ❘ 5.3 KB transferred

Console




Preserve log
.
http://live-productivity.pantheon.io/api/tracking Failed to load resource: the server responded with a status of 500 (Internal Server Error)
live-productivity.pantheon.io/api/tracking:1 POST http://live-productivity.pantheon.io/api/tracking 500 (Internal Server Error)
vendor.js:5 XHR finished loading: POST "http://live-productivity.pantheon.io/api/tracking".
.

```

**Comment by bitamar** [comment]
Payload:
```js
{
day: "14"
employee: "itamar"
issues: [{issue: 13401, label: "#1444: Script for deploying migration data", type: "dev", time: 1},…]
0: {issue: 13401, label: "#1444: Script for deploying migration data", type: "dev", time: 1}
1: {issue: 13403, label: "#1446: Updating item page", type: "dev", time: 1}
2: {issue: 13407, label: "#1448: Updating circuit live feature", type: "dev", time: 1}
3: {issue: 13408, label: "#1449: Removing Winner's auctions titles", type: "dev", time: 0.5}
length: 3.5
month: 2
period: "hour"
projectID: "27"
type: "regular"
year: 2016
}
```

**Comment by bricel** [comment]
Fixed.

**Comment by bitamar** [comment]
I'm still unable to track time (Only on Circuit)

![screen shot 2016-02-17 at 9 51 45 am](https://cloud.githubusercontent.com/assets/2283680/13103110/2910b7be-d55c-11e5-8d59-c6ed2dbcf92b.png)

**Comment by bricel** [comment]
@bitamar - Can you try again now.

**Comment by bitamar** [comment]
Works. Thanks!
